# protocol.py

CMD_MSG = "MSG"
CMD_CLIENTS = "CLIENTS"

CMD_ACK = "ACK"
CMD_NACK = "NACK"
CMD_SAVE = "SAVE"

CMD_EXISTING = "EXISTING"
CMD_NEW = "NEW"
CMD_BUSY = "BUSY" 
CMD_ACTIVE = "ACTIVE"
CMD_ALL = "ALL"

CMD_KEY = "KEY"
CMD_PUBKEY = "PUBKEY"
CMD_GETKEY = "GETKEY"
